services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: scribbledb
      POSTGRES_PASSWORD: scribbledb
      POSTGRES_DB: scribbledb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
